### PR TITLE
Refactorize repo sync worker

### PR DESCRIPTION
**Pull request by hectorperez**

### CODE REVIEW

**Comment by hectorperez** [comment]
Hi @dmarcoux, would you like to review this PR? Thanks!

If you're busy or prefer not, no problem ;)

**Comment by dmarcoux** [comment]
I'm still fairly new to Elixir, so I'll have to read a bit on Ecto and the best practices regarding how to define changesets.

**Comment by dmarcoux** [comment]
Without looking much at the code, I would like to know why the changes in the commit [Refactorize repo sync worker](https://github.com/notesclub/notesclub/pull/110/commits/f9e207ee40472d891695fbc645ffd4f3687fafaa) were done. The commit message/description are fairly generic and not explaining why this refactoring was done.

**Comment by hectorperez** [comment]
Sure. Let me describe my thought process — maybe I missed something:

First of all, in the previous [PR](https://github.com/notesclub/notesclub/pull/109/files#diff-2b0376c5a709377d56fef151f2ce2405cd17614194d3326acfbd905823e8d241L56) we got rid of `update_repo({:error, error})`. This made me think that [this](https://github.com/notesclub/notesclub/pull/110/files#diff-2b0376c5a709377d56fef151f2ce2405cd17614194d3326acfbd905823e8d241L52) can't run because it returns `{:error, error}`.

However, besides this, I'd like to refactor and improve the quality of the Notesclub code in general. For example, checking [default_branch, fork, etc](https://github.com/notesclub/notesclub/pull/110/files#diff-2b0376c5a709377d56fef151f2ce2405cd17614194d3326acfbd905823e8d241L56). in the Ecto schema is cleaner than in the worker. If I'm right, when we download new notebooks, we create a repo with everything except the `default_branch`. The `default_branch` is downloaded later in the `RepoSyncWorker` so it seems fair to make `Repos.update_repo/1` require it.

Finally, [with](https://github.com/notesclub/notesclub/pull/110/files#diff-2b0376c5a709377d56fef151f2ce2405cd17614194d3326acfbd905823e8d241R19) lets us make the flow clearer and explicit. For example, `Notebooks.enqueue_url_and_content_sync/1` was hidden inside `update_repo/1` and now it is immediate to see it.

Is it clearer now? Any questions or did I miss anything? Thanks!

**Comment by dmarcoux** [comment]
So I read on Ecto changesets and I understand them better now. Reusing the create part for the update is a good idea.

It makes sense to remove `RepoSyncWorker.update_repo/1` if it's not needed.

**Pull request merged**
